parameters:
     url_list_packages: 'https://packagist.org/packages/list.json'
     url_detail_package: 'https://packagist.org/packages/'
     
services:
      store_packages_names:
           class: UpdateBundle\ListPackages
           arguments: 
               - %url_list_packages%
               - "@old_sound_rabbit_mq.store_packages_names_producer"
               - "@doctrine.odm.mongodb.document_manager"
               
      list_packages_details:
          class: UpdateBundle\Consumer\UpdatePackagesNames
          arguments: 
              - %url_detail_package%
              - "@store_packages_details"
      store_packages_details:  
          class: UpdateBundle\DetailsPackages
          arguments: 
              - "@old_sound_rabbit_mq.store_packages_details_producer"
      persist_packages:
           class: UpdateBundle\Consumer\UpdateDatabase
           arguments: 
              - "@doctrine.odm.mongodb.document_manager"
              - "@logger"
              
          
              
              
              
           
          
         
              
              
                
            
            